#!/bin/sh
err() {
    >&2 echo "$@"
    exit 1
}

usage() {
    echo 'usage: mdrun [-h] [-l lang] [-o offline] SOURCE DEST'
}

[ "$1" = '-h' ] && usage && exit 0

lang=en
if [ "$1" = '-l' ]; then
    # validate lang from list of acceptable identifiers
    [ -z "$2" ] && usage && exit 1
    lang="$2"
    shift
    shift
fi

offline=0
if [ "$1" = '-o' ]; then
    offline=1
    shift
fi

source="$1"
dest="$2"

touch "$dest" 2> /dev/null || err "permission denied: $dest";
! [ -f "$source" ] && err "file does not exist: $source"

while true; do
    printf 'Generating ... '
    echo '
<!DOCTYPE html>
<html lang="'"$lang"'">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
' > "$dest"
if [ "$offline" = 0 ]; then
    echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/sunburst.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.min.css">
' >> "$dest"
else
    echo '<link rel="stylesheet" href="sunburst.min.css">
    <script src="highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <link rel="stylesheet" href="dark.min.css">
' >> "$dest"
fi
echo '
</head> 
<body class="container">
' >> "$dest"

    pandoc "$source" -o - >> "$dest"

    echo '
    </body>
</html>' >> "$dest"
    echo 'done'
    echo 'Waiting for changes'
    inotifywait -e close_write "$source" 2> /dev/null
done
